-- autogenerated from https://www.unicode.org/Public/15.0.0/ucd/Blocks.txt
-- |
-- Module      : Unicode.Internal.Char.Blocks
-- Copyright   : (c) 2022 Composewell Technologies and Contributors
-- License     : Apache-2.0
-- Maintainer  : streamly@composewell.com
-- Stability   : experimental

{-# LANGUAGE LambdaCase #-}
{-# OPTIONS_HADDOCK hide #-}

module Unicode.Internal.Char.Blocks
(Block(..), block, blockDefinition)
where

import Data.Ix (Ix)
import Data.Word (Word32)
import GHC.Exts
import Unicode.Internal.Bits (lookupWord32#)

-- | Unicode [block](https://www.unicode.org/glossary/#block).
--
-- There is a total of 327 blocks.
--
-- @since 0.3.1
data Block
    = BasicLatin -- ^ @U+0000..U+007F@: Basic Latin.
    | Latin1Supplement -- ^ @U+0080..U+00FF@: Latin-1 Supplement.
    | LatinExtendedA -- ^ @U+0100..U+017F@: Latin Extended-A.
    | LatinExtendedB -- ^ @U+0180..U+024F@: Latin Extended-B.
    | IPAExtensions -- ^ @U+0250..U+02AF@: IPA Extensions.
    | SpacingModifierLetters -- ^ @U+02B0..U+02FF@: Spacing Modifier Letters.
    | CombiningDiacriticalMarks -- ^ @U+0300..U+036F@: Combining Diacritical Marks.
    | GreekAndCoptic -- ^ @U+0370..U+03FF@: Greek and Coptic.
    | Cyrillic -- ^ @U+0400..U+04FF@: Cyrillic.
    | CyrillicSupplement -- ^ @U+0500..U+052F@: Cyrillic Supplement.
    | Armenian -- ^ @U+0530..U+058F@: Armenian.
    | Hebrew -- ^ @U+0590..U+05FF@: Hebrew.
    | Arabic -- ^ @U+0600..U+06FF@: Arabic.
    | Syriac -- ^ @U+0700..U+074F@: Syriac.
    | ArabicSupplement -- ^ @U+0750..U+077F@: Arabic Supplement.
    | Thaana -- ^ @U+0780..U+07BF@: Thaana.
    | NKo -- ^ @U+07C0..U+07FF@: NKo.
    | Samaritan -- ^ @U+0800..U+083F@: Samaritan.
    | Mandaic -- ^ @U+0840..U+085F@: Mandaic.
    | SyriacSupplement -- ^ @U+0860..U+086F@: Syriac Supplement.
    | ArabicExtendedB -- ^ @U+0870..U+089F@: Arabic Extended-B.
    | ArabicExtendedA -- ^ @U+08A0..U+08FF@: Arabic Extended-A.
    | Devanagari -- ^ @U+0900..U+097F@: Devanagari.
    | Bengali -- ^ @U+0980..U+09FF@: Bengali.
    | Gurmukhi -- ^ @U+0A00..U+0A7F@: Gurmukhi.
    | Gujarati -- ^ @U+0A80..U+0AFF@: Gujarati.
    | Oriya -- ^ @U+0B00..U+0B7F@: Oriya.
    | Tamil -- ^ @U+0B80..U+0BFF@: Tamil.
    | Telugu -- ^ @U+0C00..U+0C7F@: Telugu.
    | Kannada -- ^ @U+0C80..U+0CFF@: Kannada.
    | Malayalam -- ^ @U+0D00..U+0D7F@: Malayalam.
    | Sinhala -- ^ @U+0D80..U+0DFF@: Sinhala.
    | Thai -- ^ @U+0E00..U+0E7F@: Thai.
    | Lao -- ^ @U+0E80..U+0EFF@: Lao.
    | Tibetan -- ^ @U+0F00..U+0FFF@: Tibetan.
    | Myanmar -- ^ @U+1000..U+109F@: Myanmar.
    | Georgian -- ^ @U+10A0..U+10FF@: Georgian.
    | HangulJamo -- ^ @U+1100..U+11FF@: Hangul Jamo.
    | Ethiopic -- ^ @U+1200..U+137F@: Ethiopic.
    | EthiopicSupplement -- ^ @U+1380..U+139F@: Ethiopic Supplement.
    | Cherokee -- ^ @U+13A0..U+13FF@: Cherokee.
    | UnifiedCanadianAboriginalSyllabics -- ^ @U+1400..U+167F@: Unified Canadian Aboriginal Syllabics.
    | Ogham -- ^ @U+1680..U+169F@: Ogham.
    | Runic -- ^ @U+16A0..U+16FF@: Runic.
    | Tagalog -- ^ @U+1700..U+171F@: Tagalog.
    | Hanunoo -- ^ @U+1720..U+173F@: Hanunoo.
    | Buhid -- ^ @U+1740..U+175F@: Buhid.
    | Tagbanwa -- ^ @U+1760..U+177F@: Tagbanwa.
    | Khmer -- ^ @U+1780..U+17FF@: Khmer.
    | Mongolian -- ^ @U+1800..U+18AF@: Mongolian.
    | UnifiedCanadianAboriginalSyllabicsExtended -- ^ @U+18B0..U+18FF@: Unified Canadian Aboriginal Syllabics Extended.
    | Limbu -- ^ @U+1900..U+194F@: Limbu.
    | TaiLe -- ^ @U+1950..U+197F@: Tai Le.
    | NewTaiLue -- ^ @U+1980..U+19DF@: New Tai Lue.
    | KhmerSymbols -- ^ @U+19E0..U+19FF@: Khmer Symbols.
    | Buginese -- ^ @U+1A00..U+1A1F@: Buginese.
    | TaiTham -- ^ @U+1A20..U+1AAF@: Tai Tham.
    | CombiningDiacriticalMarksExtended -- ^ @U+1AB0..U+1AFF@: Combining Diacritical Marks Extended.
    | Balinese -- ^ @U+1B00..U+1B7F@: Balinese.
    | Sundanese -- ^ @U+1B80..U+1BBF@: Sundanese.
    | Batak -- ^ @U+1BC0..U+1BFF@: Batak.
    | Lepcha -- ^ @U+1C00..U+1C4F@: Lepcha.
    | OlChiki -- ^ @U+1C50..U+1C7F@: Ol Chiki.
    | CyrillicExtendedC -- ^ @U+1C80..U+1C8F@: Cyrillic Extended-C.
    | GeorgianExtended -- ^ @U+1C90..U+1CBF@: Georgian Extended.
    | SundaneseSupplement -- ^ @U+1CC0..U+1CCF@: Sundanese Supplement.
    | VedicExtensions -- ^ @U+1CD0..U+1CFF@: Vedic Extensions.
    | PhoneticExtensions -- ^ @U+1D00..U+1D7F@: Phonetic Extensions.
    | PhoneticExtensionsSupplement -- ^ @U+1D80..U+1DBF@: Phonetic Extensions Supplement.
    | CombiningDiacriticalMarksSupplement -- ^ @U+1DC0..U+1DFF@: Combining Diacritical Marks Supplement.
    | LatinExtendedAdditional -- ^ @U+1E00..U+1EFF@: Latin Extended Additional.
    | GreekExtended -- ^ @U+1F00..U+1FFF@: Greek Extended.
    | GeneralPunctuation -- ^ @U+2000..U+206F@: General Punctuation.
    | SuperscriptsAndSubscripts -- ^ @U+2070..U+209F@: Superscripts and Subscripts.
    | CurrencySymbols -- ^ @U+20A0..U+20CF@: Currency Symbols.
    | CombiningDiacriticalMarksForSymbols -- ^ @U+20D0..U+20FF@: Combining Diacritical Marks for Symbols.
    | LetterlikeSymbols -- ^ @U+2100..U+214F@: Letterlike Symbols.
    | NumberForms -- ^ @U+2150..U+218F@: Number Forms.
    | Arrows -- ^ @U+2190..U+21FF@: Arrows.
    | MathematicalOperators -- ^ @U+2200..U+22FF@: Mathematical Operators.
    | MiscellaneousTechnical -- ^ @U+2300..U+23FF@: Miscellaneous Technical.
    | ControlPictures -- ^ @U+2400..U+243F@: Control Pictures.
    | OpticalCharacterRecognition -- ^ @U+2440..U+245F@: Optical Character Recognition.
    | EnclosedAlphanumerics -- ^ @U+2460..U+24FF@: Enclosed Alphanumerics.
    | BoxDrawing -- ^ @U+2500..U+257F@: Box Drawing.
    | BlockElements -- ^ @U+2580..U+259F@: Block Elements.
    | GeometricShapes -- ^ @U+25A0..U+25FF@: Geometric Shapes.
    | MiscellaneousSymbols -- ^ @U+2600..U+26FF@: Miscellaneous Symbols.
    | Dingbats -- ^ @U+2700..U+27BF@: Dingbats.
    | MiscellaneousMathematicalSymbolsA -- ^ @U+27C0..U+27EF@: Miscellaneous Mathematical Symbols-A.
    | SupplementalArrowsA -- ^ @U+27F0..U+27FF@: Supplemental Arrows-A.
    | BraillePatterns -- ^ @U+2800..U+28FF@: Braille Patterns.
    | SupplementalArrowsB -- ^ @U+2900..U+297F@: Supplemental Arrows-B.
    | MiscellaneousMathematicalSymbolsB -- ^ @U+2980..U+29FF@: Miscellaneous Mathematical Symbols-B.
    | SupplementalMathematicalOperators -- ^ @U+2A00..U+2AFF@: Supplemental Mathematical Operators.
    | MiscellaneousSymbolsAndArrows -- ^ @U+2B00..U+2BFF@: Miscellaneous Symbols and Arrows.
    | Glagolitic -- ^ @U+2C00..U+2C5F@: Glagolitic.
    | LatinExtendedC -- ^ @U+2C60..U+2C7F@: Latin Extended-C.
    | Coptic -- ^ @U+2C80..U+2CFF@: Coptic.
    | GeorgianSupplement -- ^ @U+2D00..U+2D2F@: Georgian Supplement.
    | Tifinagh -- ^ @U+2D30..U+2D7F@: Tifinagh.
    | EthiopicExtended -- ^ @U+2D80..U+2DDF@: Ethiopic Extended.
    | CyrillicExtendedA -- ^ @U+2DE0..U+2DFF@: Cyrillic Extended-A.
    | SupplementalPunctuation -- ^ @U+2E00..U+2E7F@: Supplemental Punctuation.
    | CJKRadicalsSupplement -- ^ @U+2E80..U+2EFF@: CJK Radicals Supplement.
    | KangxiRadicals -- ^ @U+2F00..U+2FDF@: Kangxi Radicals.
    | IdeographicDescriptionCharacters -- ^ @U+2FF0..U+2FFF@: Ideographic Description Characters.
    | CJKSymbolsAndPunctuation -- ^ @U+3000..U+303F@: CJK Symbols and Punctuation.
    | Hiragana -- ^ @U+3040..U+309F@: Hiragana.
    | Katakana -- ^ @U+30A0..U+30FF@: Katakana.
    | Bopomofo -- ^ @U+3100..U+312F@: Bopomofo.
    | HangulCompatibilityJamo -- ^ @U+3130..U+318F@: Hangul Compatibility Jamo.
    | Kanbun -- ^ @U+3190..U+319F@: Kanbun.
    | BopomofoExtended -- ^ @U+31A0..U+31BF@: Bopomofo Extended.
    | CJKStrokes -- ^ @U+31C0..U+31EF@: CJK Strokes.
    | KatakanaPhoneticExtensions -- ^ @U+31F0..U+31FF@: Katakana Phonetic Extensions.
    | EnclosedCJKLettersAndMonths -- ^ @U+3200..U+32FF@: Enclosed CJK Letters and Months.
    | CJKCompatibility -- ^ @U+3300..U+33FF@: CJK Compatibility.
    | CJKUnifiedIdeographsExtensionA -- ^ @U+3400..U+4DBF@: CJK Unified Ideographs Extension A.
    | YijingHexagramSymbols -- ^ @U+4DC0..U+4DFF@: Yijing Hexagram Symbols.
    | CJKUnifiedIdeographs -- ^ @U+4E00..U+9FFF@: CJK Unified Ideographs.
    | YiSyllables -- ^ @U+A000..U+A48F@: Yi Syllables.
    | YiRadicals -- ^ @U+A490..U+A4CF@: Yi Radicals.
    | Lisu -- ^ @U+A4D0..U+A4FF@: Lisu.
    | Vai -- ^ @U+A500..U+A63F@: Vai.
    | CyrillicExtendedB -- ^ @U+A640..U+A69F@: Cyrillic Extended-B.
    | Bamum -- ^ @U+A6A0..U+A6FF@: Bamum.
    | ModifierToneLetters -- ^ @U+A700..U+A71F@: Modifier Tone Letters.
    | LatinExtendedD -- ^ @U+A720..U+A7FF@: Latin Extended-D.
    | SylotiNagri -- ^ @U+A800..U+A82F@: Syloti Nagri.
    | CommonIndicNumberForms -- ^ @U+A830..U+A83F@: Common Indic Number Forms.
    | PhagsPa -- ^ @U+A840..U+A87F@: Phags-pa.
    | Saurashtra -- ^ @U+A880..U+A8DF@: Saurashtra.
    | DevanagariExtended -- ^ @U+A8E0..U+A8FF@: Devanagari Extended.
    | KayahLi -- ^ @U+A900..U+A92F@: Kayah Li.
    | Rejang -- ^ @U+A930..U+A95F@: Rejang.
    | HangulJamoExtendedA -- ^ @U+A960..U+A97F@: Hangul Jamo Extended-A.
    | Javanese -- ^ @U+A980..U+A9DF@: Javanese.
    | MyanmarExtendedB -- ^ @U+A9E0..U+A9FF@: Myanmar Extended-B.
    | Cham -- ^ @U+AA00..U+AA5F@: Cham.
    | MyanmarExtendedA -- ^ @U+AA60..U+AA7F@: Myanmar Extended-A.
    | TaiViet -- ^ @U+AA80..U+AADF@: Tai Viet.
    | MeeteiMayekExtensions -- ^ @U+AAE0..U+AAFF@: Meetei Mayek Extensions.
    | EthiopicExtendedA -- ^ @U+AB00..U+AB2F@: Ethiopic Extended-A.
    | LatinExtendedE -- ^ @U+AB30..U+AB6F@: Latin Extended-E.
    | CherokeeSupplement -- ^ @U+AB70..U+ABBF@: Cherokee Supplement.
    | MeeteiMayek -- ^ @U+ABC0..U+ABFF@: Meetei Mayek.
    | HangulSyllables -- ^ @U+AC00..U+D7AF@: Hangul Syllables.
    | HangulJamoExtendedB -- ^ @U+D7B0..U+D7FF@: Hangul Jamo Extended-B.
    | HighSurrogates -- ^ @U+D800..U+DB7F@: High Surrogates.
    | HighPrivateUseSurrogates -- ^ @U+DB80..U+DBFF@: High Private Use Surrogates.
    | LowSurrogates -- ^ @U+DC00..U+DFFF@: Low Surrogates.
    | PrivateUseArea -- ^ @U+E000..U+F8FF@: Private Use Area.
    | CJKCompatibilityIdeographs -- ^ @U+F900..U+FAFF@: CJK Compatibility Ideographs.
    | AlphabeticPresentationForms -- ^ @U+FB00..U+FB4F@: Alphabetic Presentation Forms.
    | ArabicPresentationFormsA -- ^ @U+FB50..U+FDFF@: Arabic Presentation Forms-A.
    | VariationSelectors -- ^ @U+FE00..U+FE0F@: Variation Selectors.
    | VerticalForms -- ^ @U+FE10..U+FE1F@: Vertical Forms.
    | CombiningHalfMarks -- ^ @U+FE20..U+FE2F@: Combining Half Marks.
    | CJKCompatibilityForms -- ^ @U+FE30..U+FE4F@: CJK Compatibility Forms.
    | SmallFormVariants -- ^ @U+FE50..U+FE6F@: Small Form Variants.
    | ArabicPresentationFormsB -- ^ @U+FE70..U+FEFF@: Arabic Presentation Forms-B.
    | HalfwidthAndFullwidthForms -- ^ @U+FF00..U+FFEF@: Halfwidth and Fullwidth Forms.
    | Specials -- ^ @U+FFF0..U+FFFF@: Specials.
    | LinearBSyllabary -- ^ @U+10000..U+1007F@: Linear B Syllabary.
    | LinearBIdeograms -- ^ @U+10080..U+100FF@: Linear B Ideograms.
    | AegeanNumbers -- ^ @U+10100..U+1013F@: Aegean Numbers.
    | AncientGreekNumbers -- ^ @U+10140..U+1018F@: Ancient Greek Numbers.
    | AncientSymbols -- ^ @U+10190..U+101CF@: Ancient Symbols.
    | PhaistosDisc -- ^ @U+101D0..U+101FF@: Phaistos Disc.
    | Lycian -- ^ @U+10280..U+1029F@: Lycian.
    | Carian -- ^ @U+102A0..U+102DF@: Carian.
    | CopticEpactNumbers -- ^ @U+102E0..U+102FF@: Coptic Epact Numbers.
    | OldItalic -- ^ @U+10300..U+1032F@: Old Italic.
    | Gothic -- ^ @U+10330..U+1034F@: Gothic.
    | OldPermic -- ^ @U+10350..U+1037F@: Old Permic.
    | Ugaritic -- ^ @U+10380..U+1039F@: Ugaritic.
    | OldPersian -- ^ @U+103A0..U+103DF@: Old Persian.
    | Deseret -- ^ @U+10400..U+1044F@: Deseret.
    | Shavian -- ^ @U+10450..U+1047F@: Shavian.
    | Osmanya -- ^ @U+10480..U+104AF@: Osmanya.
    | Osage -- ^ @U+104B0..U+104FF@: Osage.
    | Elbasan -- ^ @U+10500..U+1052F@: Elbasan.
    | CaucasianAlbanian -- ^ @U+10530..U+1056F@: Caucasian Albanian.
    | Vithkuqi -- ^ @U+10570..U+105BF@: Vithkuqi.
    | LinearA -- ^ @U+10600..U+1077F@: Linear A.
    | LatinExtendedF -- ^ @U+10780..U+107BF@: Latin Extended-F.
    | CypriotSyllabary -- ^ @U+10800..U+1083F@: Cypriot Syllabary.
    | ImperialAramaic -- ^ @U+10840..U+1085F@: Imperial Aramaic.
    | Palmyrene -- ^ @U+10860..U+1087F@: Palmyrene.
    | Nabataean -- ^ @U+10880..U+108AF@: Nabataean.
    | Hatran -- ^ @U+108E0..U+108FF@: Hatran.
    | Phoenician -- ^ @U+10900..U+1091F@: Phoenician.
    | Lydian -- ^ @U+10920..U+1093F@: Lydian.
    | MeroiticHieroglyphs -- ^ @U+10980..U+1099F@: Meroitic Hieroglyphs.
    | MeroiticCursive -- ^ @U+109A0..U+109FF@: Meroitic Cursive.
    | Kharoshthi -- ^ @U+10A00..U+10A5F@: Kharoshthi.
    | OldSouthArabian -- ^ @U+10A60..U+10A7F@: Old South Arabian.
    | OldNorthArabian -- ^ @U+10A80..U+10A9F@: Old North Arabian.
    | Manichaean -- ^ @U+10AC0..U+10AFF@: Manichaean.
    | Avestan -- ^ @U+10B00..U+10B3F@: Avestan.
    | InscriptionalParthian -- ^ @U+10B40..U+10B5F@: Inscriptional Parthian.
    | InscriptionalPahlavi -- ^ @U+10B60..U+10B7F@: Inscriptional Pahlavi.
    | PsalterPahlavi -- ^ @U+10B80..U+10BAF@: Psalter Pahlavi.
    | OldTurkic -- ^ @U+10C00..U+10C4F@: Old Turkic.
    | OldHungarian -- ^ @U+10C80..U+10CFF@: Old Hungarian.
    | HanifiRohingya -- ^ @U+10D00..U+10D3F@: Hanifi Rohingya.
    | RumiNumeralSymbols -- ^ @U+10E60..U+10E7F@: Rumi Numeral Symbols.
    | Yezidi -- ^ @U+10E80..U+10EBF@: Yezidi.
    | ArabicExtendedC -- ^ @U+10EC0..U+10EFF@: Arabic Extended-C.
    | OldSogdian -- ^ @U+10F00..U+10F2F@: Old Sogdian.
    | Sogdian -- ^ @U+10F30..U+10F6F@: Sogdian.
    | OldUyghur -- ^ @U+10F70..U+10FAF@: Old Uyghur.
    | Chorasmian -- ^ @U+10FB0..U+10FDF@: Chorasmian.
    | Elymaic -- ^ @U+10FE0..U+10FFF@: Elymaic.
    | Brahmi -- ^ @U+11000..U+1107F@: Brahmi.
    | Kaithi -- ^ @U+11080..U+110CF@: Kaithi.
    | SoraSompeng -- ^ @U+110D0..U+110FF@: Sora Sompeng.
    | Chakma -- ^ @U+11100..U+1114F@: Chakma.
    | Mahajani -- ^ @U+11150..U+1117F@: Mahajani.
    | Sharada -- ^ @U+11180..U+111DF@: Sharada.
    | SinhalaArchaicNumbers -- ^ @U+111E0..U+111FF@: Sinhala Archaic Numbers.
    | Khojki -- ^ @U+11200..U+1124F@: Khojki.
    | Multani -- ^ @U+11280..U+112AF@: Multani.
    | Khudawadi -- ^ @U+112B0..U+112FF@: Khudawadi.
    | Grantha -- ^ @U+11300..U+1137F@: Grantha.
    | Newa -- ^ @U+11400..U+1147F@: Newa.
    | Tirhuta -- ^ @U+11480..U+114DF@: Tirhuta.
    | Siddham -- ^ @U+11580..U+115FF@: Siddham.
    | Modi -- ^ @U+11600..U+1165F@: Modi.
    | MongolianSupplement -- ^ @U+11660..U+1167F@: Mongolian Supplement.
    | Takri -- ^ @U+11680..U+116CF@: Takri.
    | Ahom -- ^ @U+11700..U+1174F@: Ahom.
    | Dogra -- ^ @U+11800..U+1184F@: Dogra.
    | WarangCiti -- ^ @U+118A0..U+118FF@: Warang Citi.
    | DivesAkuru -- ^ @U+11900..U+1195F@: Dives Akuru.
    | Nandinagari -- ^ @U+119A0..U+119FF@: Nandinagari.
    | ZanabazarSquare -- ^ @U+11A00..U+11A4F@: Zanabazar Square.
    | Soyombo -- ^ @U+11A50..U+11AAF@: Soyombo.
    | UnifiedCanadianAboriginalSyllabicsExtendedA -- ^ @U+11AB0..U+11ABF@: Unified Canadian Aboriginal Syllabics Extended-A.
    | PauCinHau -- ^ @U+11AC0..U+11AFF@: Pau Cin Hau.
    | DevanagariExtendedA -- ^ @U+11B00..U+11B5F@: Devanagari Extended-A.
    | Bhaiksuki -- ^ @U+11C00..U+11C6F@: Bhaiksuki.
    | Marchen -- ^ @U+11C70..U+11CBF@: Marchen.
    | MasaramGondi -- ^ @U+11D00..U+11D5F@: Masaram Gondi.
    | GunjalaGondi -- ^ @U+11D60..U+11DAF@: Gunjala Gondi.
    | Makasar -- ^ @U+11EE0..U+11EFF@: Makasar.
    | Kawi -- ^ @U+11F00..U+11F5F@: Kawi.
    | LisuSupplement -- ^ @U+11FB0..U+11FBF@: Lisu Supplement.
    | TamilSupplement -- ^ @U+11FC0..U+11FFF@: Tamil Supplement.
    | Cuneiform -- ^ @U+12000..U+123FF@: Cuneiform.
    | CuneiformNumbersAndPunctuation -- ^ @U+12400..U+1247F@: Cuneiform Numbers and Punctuation.
    | EarlyDynasticCuneiform -- ^ @U+12480..U+1254F@: Early Dynastic Cuneiform.
    | CyproMinoan -- ^ @U+12F90..U+12FFF@: Cypro-Minoan.
    | EgyptianHieroglyphs -- ^ @U+13000..U+1342F@: Egyptian Hieroglyphs.
    | EgyptianHieroglyphFormatControls -- ^ @U+13430..U+1345F@: Egyptian Hieroglyph Format Controls.
    | AnatolianHieroglyphs -- ^ @U+14400..U+1467F@: Anatolian Hieroglyphs.
    | BamumSupplement -- ^ @U+16800..U+16A3F@: Bamum Supplement.
    | Mro -- ^ @U+16A40..U+16A6F@: Mro.
    | Tangsa -- ^ @U+16A70..U+16ACF@: Tangsa.
    | BassaVah -- ^ @U+16AD0..U+16AFF@: Bassa Vah.
    | PahawhHmong -- ^ @U+16B00..U+16B8F@: Pahawh Hmong.
    | Medefaidrin -- ^ @U+16E40..U+16E9F@: Medefaidrin.
    | Miao -- ^ @U+16F00..U+16F9F@: Miao.
    | IdeographicSymbolsAndPunctuation -- ^ @U+16FE0..U+16FFF@: Ideographic Symbols and Punctuation.
    | Tangut -- ^ @U+17000..U+187FF@: Tangut.
    | TangutComponents -- ^ @U+18800..U+18AFF@: Tangut Components.
    | KhitanSmallScript -- ^ @U+18B00..U+18CFF@: Khitan Small Script.
    | TangutSupplement -- ^ @U+18D00..U+18D7F@: Tangut Supplement.
    | KanaExtendedB -- ^ @U+1AFF0..U+1AFFF@: Kana Extended-B.
    | KanaSupplement -- ^ @U+1B000..U+1B0FF@: Kana Supplement.
    | KanaExtendedA -- ^ @U+1B100..U+1B12F@: Kana Extended-A.
    | SmallKanaExtension -- ^ @U+1B130..U+1B16F@: Small Kana Extension.
    | Nushu -- ^ @U+1B170..U+1B2FF@: Nushu.
    | Duployan -- ^ @U+1BC00..U+1BC9F@: Duployan.
    | ShorthandFormatControls -- ^ @U+1BCA0..U+1BCAF@: Shorthand Format Controls.
    | ZnamennyMusicalNotation -- ^ @U+1CF00..U+1CFCF@: Znamenny Musical Notation.
    | ByzantineMusicalSymbols -- ^ @U+1D000..U+1D0FF@: Byzantine Musical Symbols.
    | MusicalSymbols -- ^ @U+1D100..U+1D1FF@: Musical Symbols.
    | AncientGreekMusicalNotation -- ^ @U+1D200..U+1D24F@: Ancient Greek Musical Notation.
    | KaktovikNumerals -- ^ @U+1D2C0..U+1D2DF@: Kaktovik Numerals.
    | MayanNumerals -- ^ @U+1D2E0..U+1D2FF@: Mayan Numerals.
    | TaiXuanJingSymbols -- ^ @U+1D300..U+1D35F@: Tai Xuan Jing Symbols.
    | CountingRodNumerals -- ^ @U+1D360..U+1D37F@: Counting Rod Numerals.
    | MathematicalAlphanumericSymbols -- ^ @U+1D400..U+1D7FF@: Mathematical Alphanumeric Symbols.
    | SuttonSignWriting -- ^ @U+1D800..U+1DAAF@: Sutton SignWriting.
    | LatinExtendedG -- ^ @U+1DF00..U+1DFFF@: Latin Extended-G.
    | GlagoliticSupplement -- ^ @U+1E000..U+1E02F@: Glagolitic Supplement.
    | CyrillicExtendedD -- ^ @U+1E030..U+1E08F@: Cyrillic Extended-D.
    | NyiakengPuachueHmong -- ^ @U+1E100..U+1E14F@: Nyiakeng Puachue Hmong.
    | Toto -- ^ @U+1E290..U+1E2BF@: Toto.
    | Wancho -- ^ @U+1E2C0..U+1E2FF@: Wancho.
    | NagMundari -- ^ @U+1E4D0..U+1E4FF@: Nag Mundari.
    | EthiopicExtendedB -- ^ @U+1E7E0..U+1E7FF@: Ethiopic Extended-B.
    | MendeKikakui -- ^ @U+1E800..U+1E8DF@: Mende Kikakui.
    | Adlam -- ^ @U+1E900..U+1E95F@: Adlam.
    | IndicSiyaqNumbers -- ^ @U+1EC70..U+1ECBF@: Indic Siyaq Numbers.
    | OttomanSiyaqNumbers -- ^ @U+1ED00..U+1ED4F@: Ottoman Siyaq Numbers.
    | ArabicMathematicalAlphabeticSymbols -- ^ @U+1EE00..U+1EEFF@: Arabic Mathematical Alphabetic Symbols.
    | MahjongTiles -- ^ @U+1F000..U+1F02F@: Mahjong Tiles.
    | DominoTiles -- ^ @U+1F030..U+1F09F@: Domino Tiles.
    | PlayingCards -- ^ @U+1F0A0..U+1F0FF@: Playing Cards.
    | EnclosedAlphanumericSupplement -- ^ @U+1F100..U+1F1FF@: Enclosed Alphanumeric Supplement.
    | EnclosedIdeographicSupplement -- ^ @U+1F200..U+1F2FF@: Enclosed Ideographic Supplement.
    | MiscellaneousSymbolsAndPictographs -- ^ @U+1F300..U+1F5FF@: Miscellaneous Symbols and Pictographs.
    | Emoticons -- ^ @U+1F600..U+1F64F@: Emoticons.
    | OrnamentalDingbats -- ^ @U+1F650..U+1F67F@: Ornamental Dingbats.
    | TransportAndMapSymbols -- ^ @U+1F680..U+1F6FF@: Transport and Map Symbols.
    | AlchemicalSymbols -- ^ @U+1F700..U+1F77F@: Alchemical Symbols.
    | GeometricShapesExtended -- ^ @U+1F780..U+1F7FF@: Geometric Shapes Extended.
    | SupplementalArrowsC -- ^ @U+1F800..U+1F8FF@: Supplemental Arrows-C.
    | SupplementalSymbolsAndPictographs -- ^ @U+1F900..U+1F9FF@: Supplemental Symbols and Pictographs.
    | ChessSymbols -- ^ @U+1FA00..U+1FA6F@: Chess Symbols.
    | SymbolsAndPictographsExtendedA -- ^ @U+1FA70..U+1FAFF@: Symbols and Pictographs Extended-A.
    | SymbolsForLegacyComputing -- ^ @U+1FB00..U+1FBFF@: Symbols for Legacy Computing.
    | CJKUnifiedIdeographsExtensionB -- ^ @U+20000..U+2A6DF@: CJK Unified Ideographs Extension B.
    | CJKUnifiedIdeographsExtensionC -- ^ @U+2A700..U+2B73F@: CJK Unified Ideographs Extension C.
    | CJKUnifiedIdeographsExtensionD -- ^ @U+2B740..U+2B81F@: CJK Unified Ideographs Extension D.
    | CJKUnifiedIdeographsExtensionE -- ^ @U+2B820..U+2CEAF@: CJK Unified Ideographs Extension E.
    | CJKUnifiedIdeographsExtensionF -- ^ @U+2CEB0..U+2EBEF@: CJK Unified Ideographs Extension F.
    | CJKCompatibilityIdeographsSupplement -- ^ @U+2F800..U+2FA1F@: CJK Compatibility Ideographs Supplement.
    | CJKUnifiedIdeographsExtensionG -- ^ @U+30000..U+3134F@: CJK Unified Ideographs Extension G.
    | CJKUnifiedIdeographsExtensionH -- ^ @U+31350..U+323AF@: CJK Unified Ideographs Extension H.
    | Tags -- ^ @U+E0000..U+E007F@: Tags.
    | VariationSelectorsSupplement -- ^ @U+E0100..U+E01EF@: Variation Selectors Supplement.
    | SupplementaryPrivateUseAreaA -- ^ @U+F0000..U+FFFFF@: Supplementary Private Use Area-A.
    | SupplementaryPrivateUseAreaB -- ^ @U+100000..U+10FFFF@: Supplementary Private Use Area-B.
    deriving (Enum, Bounded, Eq, Ord, Ix, Show)

-- | Block definition
--
-- Undefined for values greater than 325.
--
-- Encoding:
--
-- * Lower bound (UTF-32LE)
-- * Upper bound (UTF-32LE)
-- * Name (null terminated ASCII string)
--
-- @since 0.3.1
blockDefinition :: Int# -> Addr#
blockDefinition = \case
    0# -> "\0\0\0\0\127\0\0\0Basic Latin\0"#
    1# -> "\128\0\0\0\255\0\0\0Latin-1 Supplement\0"#
    2# -> "\0\1\0\0\127\1\0\0Latin Extended-A\0"#
    3# -> "\128\1\0\0\79\2\0\0Latin Extended-B\0"#
    4# -> "\80\2\0\0\175\2\0\0IPA Extensions\0"#
    5# -> "\176\2\0\0\255\2\0\0Spacing Modifier Letters\0"#
    6# -> "\0\3\0\0\111\3\0\0Combining Diacritical Marks\0"#
    7# -> "\112\3\0\0\255\3\0\0Greek and Coptic\0"#
    8# -> "\0\4\0\0\255\4\0\0Cyrillic\0"#
    9# -> "\0\5\0\0\47\5\0\0Cyrillic Supplement\0"#
    10# -> "\48\5\0\0\143\5\0\0Armenian\0"#
    11# -> "\144\5\0\0\255\5\0\0Hebrew\0"#
    12# -> "\0\6\0\0\255\6\0\0Arabic\0"#
    13# -> "\0\7\0\0\79\7\0\0Syriac\0"#
    14# -> "\80\7\0\0\127\7\0\0Arabic Supplement\0"#
    15# -> "\128\7\0\0\191\7\0\0Thaana\0"#
    16# -> "\192\7\0\0\255\7\0\0NKo\0"#
    17# -> "\0\8\0\0\63\8\0\0Samaritan\0"#
    18# -> "\64\8\0\0\95\8\0\0Mandaic\0"#
    19# -> "\96\8\0\0\111\8\0\0Syriac Supplement\0"#
    20# -> "\112\8\0\0\159\8\0\0Arabic Extended-B\0"#
    21# -> "\160\8\0\0\255\8\0\0Arabic Extended-A\0"#
    22# -> "\0\9\0\0\127\9\0\0Devanagari\0"#
    23# -> "\128\9\0\0\255\9\0\0Bengali\0"#
    24# -> "\0\10\0\0\127\10\0\0Gurmukhi\0"#
    25# -> "\128\10\0\0\255\10\0\0Gujarati\0"#
    26# -> "\0\11\0\0\127\11\0\0Oriya\0"#
    27# -> "\128\11\0\0\255\11\0\0Tamil\0"#
    28# -> "\0\12\0\0\127\12\0\0Telugu\0"#
    29# -> "\128\12\0\0\255\12\0\0Kannada\0"#
    30# -> "\0\13\0\0\127\13\0\0Malayalam\0"#
    31# -> "\128\13\0\0\255\13\0\0Sinhala\0"#
    32# -> "\0\14\0\0\127\14\0\0Thai\0"#
    33# -> "\128\14\0\0\255\14\0\0Lao\0"#
    34# -> "\0\15\0\0\255\15\0\0Tibetan\0"#
    35# -> "\0\16\0\0\159\16\0\0Myanmar\0"#
    36# -> "\160\16\0\0\255\16\0\0Georgian\0"#
    37# -> "\0\17\0\0\255\17\0\0Hangul Jamo\0"#
    38# -> "\0\18\0\0\127\19\0\0Ethiopic\0"#
    39# -> "\128\19\0\0\159\19\0\0Ethiopic Supplement\0"#
    40# -> "\160\19\0\0\255\19\0\0Cherokee\0"#
    41# -> "\0\20\0\0\127\22\0\0Unified Canadian Aboriginal Syllabics\0"#
    42# -> "\128\22\0\0\159\22\0\0Ogham\0"#
    43# -> "\160\22\0\0\255\22\0\0Runic\0"#
    44# -> "\0\23\0\0\31\23\0\0Tagalog\0"#
    45# -> "\32\23\0\0\63\23\0\0Hanunoo\0"#
    46# -> "\64\23\0\0\95\23\0\0Buhid\0"#
    47# -> "\96\23\0\0\127\23\0\0Tagbanwa\0"#
    48# -> "\128\23\0\0\255\23\0\0Khmer\0"#
    49# -> "\0\24\0\0\175\24\0\0Mongolian\0"#
    50# -> "\176\24\0\0\255\24\0\0Unified Canadian Aboriginal Syllabics Extended\0"#
    51# -> "\0\25\0\0\79\25\0\0Limbu\0"#
    52# -> "\80\25\0\0\127\25\0\0Tai Le\0"#
    53# -> "\128\25\0\0\223\25\0\0New Tai Lue\0"#
    54# -> "\224\25\0\0\255\25\0\0Khmer Symbols\0"#
    55# -> "\0\26\0\0\31\26\0\0Buginese\0"#
    56# -> "\32\26\0\0\175\26\0\0Tai Tham\0"#
    57# -> "\176\26\0\0\255\26\0\0Combining Diacritical Marks Extended\0"#
    58# -> "\0\27\0\0\127\27\0\0Balinese\0"#
    59# -> "\128\27\0\0\191\27\0\0Sundanese\0"#
    60# -> "\192\27\0\0\255\27\0\0Batak\0"#
    61# -> "\0\28\0\0\79\28\0\0Lepcha\0"#
    62# -> "\80\28\0\0\127\28\0\0Ol Chiki\0"#
    63# -> "\128\28\0\0\143\28\0\0Cyrillic Extended-C\0"#
    64# -> "\144\28\0\0\191\28\0\0Georgian Extended\0"#
    65# -> "\192\28\0\0\207\28\0\0Sundanese Supplement\0"#
    66# -> "\208\28\0\0\255\28\0\0Vedic Extensions\0"#
    67# -> "\0\29\0\0\127\29\0\0Phonetic Extensions\0"#
    68# -> "\128\29\0\0\191\29\0\0Phonetic Extensions Supplement\0"#
    69# -> "\192\29\0\0\255\29\0\0Combining Diacritical Marks Supplement\0"#
    70# -> "\0\30\0\0\255\30\0\0Latin Extended Additional\0"#
    71# -> "\0\31\0\0\255\31\0\0Greek Extended\0"#
    72# -> "\0\32\0\0\111\32\0\0General Punctuation\0"#
    73# -> "\112\32\0\0\159\32\0\0Superscripts and Subscripts\0"#
    74# -> "\160\32\0\0\207\32\0\0Currency Symbols\0"#
    75# -> "\208\32\0\0\255\32\0\0Combining Diacritical Marks for Symbols\0"#
    76# -> "\0\33\0\0\79\33\0\0Letterlike Symbols\0"#
    77# -> "\80\33\0\0\143\33\0\0Number Forms\0"#
    78# -> "\144\33\0\0\255\33\0\0Arrows\0"#
    79# -> "\0\34\0\0\255\34\0\0Mathematical Operators\0"#
    80# -> "\0\35\0\0\255\35\0\0Miscellaneous Technical\0"#
    81# -> "\0\36\0\0\63\36\0\0Control Pictures\0"#
    82# -> "\64\36\0\0\95\36\0\0Optical Character Recognition\0"#
    83# -> "\96\36\0\0\255\36\0\0Enclosed Alphanumerics\0"#
    84# -> "\0\37\0\0\127\37\0\0Box Drawing\0"#
    85# -> "\128\37\0\0\159\37\0\0Block Elements\0"#
    86# -> "\160\37\0\0\255\37\0\0Geometric Shapes\0"#
    87# -> "\0\38\0\0\255\38\0\0Miscellaneous Symbols\0"#
    88# -> "\0\39\0\0\191\39\0\0Dingbats\0"#
    89# -> "\192\39\0\0\239\39\0\0Miscellaneous Mathematical Symbols-A\0"#
    90# -> "\240\39\0\0\255\39\0\0Supplemental Arrows-A\0"#
    91# -> "\0\40\0\0\255\40\0\0Braille Patterns\0"#
    92# -> "\0\41\0\0\127\41\0\0Supplemental Arrows-B\0"#
    93# -> "\128\41\0\0\255\41\0\0Miscellaneous Mathematical Symbols-B\0"#
    94# -> "\0\42\0\0\255\42\0\0Supplemental Mathematical Operators\0"#
    95# -> "\0\43\0\0\255\43\0\0Miscellaneous Symbols and Arrows\0"#
    96# -> "\0\44\0\0\95\44\0\0Glagolitic\0"#
    97# -> "\96\44\0\0\127\44\0\0Latin Extended-C\0"#
    98# -> "\128\44\0\0\255\44\0\0Coptic\0"#
    99# -> "\0\45\0\0\47\45\0\0Georgian Supplement\0"#
    100# -> "\48\45\0\0\127\45\0\0Tifinagh\0"#
    101# -> "\128\45\0\0\223\45\0\0Ethiopic Extended\0"#
    102# -> "\224\45\0\0\255\45\0\0Cyrillic Extended-A\0"#
    103# -> "\0\46\0\0\127\46\0\0Supplemental Punctuation\0"#
    104# -> "\128\46\0\0\255\46\0\0CJK Radicals Supplement\0"#
    105# -> "\0\47\0\0\223\47\0\0Kangxi Radicals\0"#
    106# -> "\240\47\0\0\255\47\0\0Ideographic Description Characters\0"#
    107# -> "\0\48\0\0\63\48\0\0CJK Symbols and Punctuation\0"#
    108# -> "\64\48\0\0\159\48\0\0Hiragana\0"#
    109# -> "\160\48\0\0\255\48\0\0Katakana\0"#
    110# -> "\0\49\0\0\47\49\0\0Bopomofo\0"#
    111# -> "\48\49\0\0\143\49\0\0Hangul Compatibility Jamo\0"#
    112# -> "\144\49\0\0\159\49\0\0Kanbun\0"#
    113# -> "\160\49\0\0\191\49\0\0Bopomofo Extended\0"#
    114# -> "\192\49\0\0\239\49\0\0CJK Strokes\0"#
    115# -> "\240\49\0\0\255\49\0\0Katakana Phonetic Extensions\0"#
    116# -> "\0\50\0\0\255\50\0\0Enclosed CJK Letters and Months\0"#
    117# -> "\0\51\0\0\255\51\0\0CJK Compatibility\0"#
    118# -> "\0\52\0\0\191\77\0\0CJK Unified Ideographs Extension A\0"#
    119# -> "\192\77\0\0\255\77\0\0Yijing Hexagram Symbols\0"#
    120# -> "\0\78\0\0\255\159\0\0CJK Unified Ideographs\0"#
    121# -> "\0\160\0\0\143\164\0\0Yi Syllables\0"#
    122# -> "\144\164\0\0\207\164\0\0Yi Radicals\0"#
    123# -> "\208\164\0\0\255\164\0\0Lisu\0"#
    124# -> "\0\165\0\0\63\166\0\0Vai\0"#
    125# -> "\64\166\0\0\159\166\0\0Cyrillic Extended-B\0"#
    126# -> "\160\166\0\0\255\166\0\0Bamum\0"#
    127# -> "\0\167\0\0\31\167\0\0Modifier Tone Letters\0"#
    128# -> "\32\167\0\0\255\167\0\0Latin Extended-D\0"#
    129# -> "\0\168\0\0\47\168\0\0Syloti Nagri\0"#
    130# -> "\48\168\0\0\63\168\0\0Common Indic Number Forms\0"#
    131# -> "\64\168\0\0\127\168\0\0Phags-pa\0"#
    132# -> "\128\168\0\0\223\168\0\0Saurashtra\0"#
    133# -> "\224\168\0\0\255\168\0\0Devanagari Extended\0"#
    134# -> "\0\169\0\0\47\169\0\0Kayah Li\0"#
    135# -> "\48\169\0\0\95\169\0\0Rejang\0"#
    136# -> "\96\169\0\0\127\169\0\0Hangul Jamo Extended-A\0"#
    137# -> "\128\169\0\0\223\169\0\0Javanese\0"#
    138# -> "\224\169\0\0\255\169\0\0Myanmar Extended-B\0"#
    139# -> "\0\170\0\0\95\170\0\0Cham\0"#
    140# -> "\96\170\0\0\127\170\0\0Myanmar Extended-A\0"#
    141# -> "\128\170\0\0\223\170\0\0Tai Viet\0"#
    142# -> "\224\170\0\0\255\170\0\0Meetei Mayek Extensions\0"#
    143# -> "\0\171\0\0\47\171\0\0Ethiopic Extended-A\0"#
    144# -> "\48\171\0\0\111\171\0\0Latin Extended-E\0"#
    145# -> "\112\171\0\0\191\171\0\0Cherokee Supplement\0"#
    146# -> "\192\171\0\0\255\171\0\0Meetei Mayek\0"#
    147# -> "\0\172\0\0\175\215\0\0Hangul Syllables\0"#
    148# -> "\176\215\0\0\255\215\0\0Hangul Jamo Extended-B\0"#
    149# -> "\0\216\0\0\127\219\0\0High Surrogates\0"#
    150# -> "\128\219\0\0\255\219\0\0High Private Use Surrogates\0"#
    151# -> "\0\220\0\0\255\223\0\0Low Surrogates\0"#
    152# -> "\0\224\0\0\255\248\0\0Private Use Area\0"#
    153# -> "\0\249\0\0\255\250\0\0CJK Compatibility Ideographs\0"#
    154# -> "\0\251\0\0\79\251\0\0Alphabetic Presentation Forms\0"#
    155# -> "\80\251\0\0\255\253\0\0Arabic Presentation Forms-A\0"#
    156# -> "\0\254\0\0\15\254\0\0Variation Selectors\0"#
    157# -> "\16\254\0\0\31\254\0\0Vertical Forms\0"#
    158# -> "\32\254\0\0\47\254\0\0Combining Half Marks\0"#
    159# -> "\48\254\0\0\79\254\0\0CJK Compatibility Forms\0"#
    160# -> "\80\254\0\0\111\254\0\0Small Form Variants\0"#
    161# -> "\112\254\0\0\255\254\0\0Arabic Presentation Forms-B\0"#
    162# -> "\0\255\0\0\239\255\0\0Halfwidth and Fullwidth Forms\0"#
    163# -> "\240\255\0\0\255\255\0\0Specials\0"#
    164# -> "\0\0\1\0\127\0\1\0Linear B Syllabary\0"#
    165# -> "\128\0\1\0\255\0\1\0Linear B Ideograms\0"#
    166# -> "\0\1\1\0\63\1\1\0Aegean Numbers\0"#
    167# -> "\64\1\1\0\143\1\1\0Ancient Greek Numbers\0"#
    168# -> "\144\1\1\0\207\1\1\0Ancient Symbols\0"#
    169# -> "\208\1\1\0\255\1\1\0Phaistos Disc\0"#
    170# -> "\128\2\1\0\159\2\1\0Lycian\0"#
    171# -> "\160\2\1\0\223\2\1\0Carian\0"#
    172# -> "\224\2\1\0\255\2\1\0Coptic Epact Numbers\0"#
    173# -> "\0\3\1\0\47\3\1\0Old Italic\0"#
    174# -> "\48\3\1\0\79\3\1\0Gothic\0"#
    175# -> "\80\3\1\0\127\3\1\0Old Permic\0"#
    176# -> "\128\3\1\0\159\3\1\0Ugaritic\0"#
    177# -> "\160\3\1\0\223\3\1\0Old Persian\0"#
    178# -> "\0\4\1\0\79\4\1\0Deseret\0"#
    179# -> "\80\4\1\0\127\4\1\0Shavian\0"#
    180# -> "\128\4\1\0\175\4\1\0Osmanya\0"#
    181# -> "\176\4\1\0\255\4\1\0Osage\0"#
    182# -> "\0\5\1\0\47\5\1\0Elbasan\0"#
    183# -> "\48\5\1\0\111\5\1\0Caucasian Albanian\0"#
    184# -> "\112\5\1\0\191\5\1\0Vithkuqi\0"#
    185# -> "\0\6\1\0\127\7\1\0Linear A\0"#
    186# -> "\128\7\1\0\191\7\1\0Latin Extended-F\0"#
    187# -> "\0\8\1\0\63\8\1\0Cypriot Syllabary\0"#
    188# -> "\64\8\1\0\95\8\1\0Imperial Aramaic\0"#
    189# -> "\96\8\1\0\127\8\1\0Palmyrene\0"#
    190# -> "\128\8\1\0\175\8\1\0Nabataean\0"#
    191# -> "\224\8\1\0\255\8\1\0Hatran\0"#
    192# -> "\0\9\1\0\31\9\1\0Phoenician\0"#
    193# -> "\32\9\1\0\63\9\1\0Lydian\0"#
    194# -> "\128\9\1\0\159\9\1\0Meroitic Hieroglyphs\0"#
    195# -> "\160\9\1\0\255\9\1\0Meroitic Cursive\0"#
    196# -> "\0\10\1\0\95\10\1\0Kharoshthi\0"#
    197# -> "\96\10\1\0\127\10\1\0Old South Arabian\0"#
    198# -> "\128\10\1\0\159\10\1\0Old North Arabian\0"#
    199# -> "\192\10\1\0\255\10\1\0Manichaean\0"#
    200# -> "\0\11\1\0\63\11\1\0Avestan\0"#
    201# -> "\64\11\1\0\95\11\1\0Inscriptional Parthian\0"#
    202# -> "\96\11\1\0\127\11\1\0Inscriptional Pahlavi\0"#
    203# -> "\128\11\1\0\175\11\1\0Psalter Pahlavi\0"#
    204# -> "\0\12\1\0\79\12\1\0Old Turkic\0"#
    205# -> "\128\12\1\0\255\12\1\0Old Hungarian\0"#
    206# -> "\0\13\1\0\63\13\1\0Hanifi Rohingya\0"#
    207# -> "\96\14\1\0\127\14\1\0Rumi Numeral Symbols\0"#
    208# -> "\128\14\1\0\191\14\1\0Yezidi\0"#
    209# -> "\192\14\1\0\255\14\1\0Arabic Extended-C\0"#
    210# -> "\0\15\1\0\47\15\1\0Old Sogdian\0"#
    211# -> "\48\15\1\0\111\15\1\0Sogdian\0"#
    212# -> "\112\15\1\0\175\15\1\0Old Uyghur\0"#
    213# -> "\176\15\1\0\223\15\1\0Chorasmian\0"#
    214# -> "\224\15\1\0\255\15\1\0Elymaic\0"#
    215# -> "\0\16\1\0\127\16\1\0Brahmi\0"#
    216# -> "\128\16\1\0\207\16\1\0Kaithi\0"#
    217# -> "\208\16\1\0\255\16\1\0Sora Sompeng\0"#
    218# -> "\0\17\1\0\79\17\1\0Chakma\0"#
    219# -> "\80\17\1\0\127\17\1\0Mahajani\0"#
    220# -> "\128\17\1\0\223\17\1\0Sharada\0"#
    221# -> "\224\17\1\0\255\17\1\0Sinhala Archaic Numbers\0"#
    222# -> "\0\18\1\0\79\18\1\0Khojki\0"#
    223# -> "\128\18\1\0\175\18\1\0Multani\0"#
    224# -> "\176\18\1\0\255\18\1\0Khudawadi\0"#
    225# -> "\0\19\1\0\127\19\1\0Grantha\0"#
    226# -> "\0\20\1\0\127\20\1\0Newa\0"#
    227# -> "\128\20\1\0\223\20\1\0Tirhuta\0"#
    228# -> "\128\21\1\0\255\21\1\0Siddham\0"#
    229# -> "\0\22\1\0\95\22\1\0Modi\0"#
    230# -> "\96\22\1\0\127\22\1\0Mongolian Supplement\0"#
    231# -> "\128\22\1\0\207\22\1\0Takri\0"#
    232# -> "\0\23\1\0\79\23\1\0Ahom\0"#
    233# -> "\0\24\1\0\79\24\1\0Dogra\0"#
    234# -> "\160\24\1\0\255\24\1\0Warang Citi\0"#
    235# -> "\0\25\1\0\95\25\1\0Dives Akuru\0"#
    236# -> "\160\25\1\0\255\25\1\0Nandinagari\0"#
    237# -> "\0\26\1\0\79\26\1\0Zanabazar Square\0"#
    238# -> "\80\26\1\0\175\26\1\0Soyombo\0"#
    239# -> "\176\26\1\0\191\26\1\0Unified Canadian Aboriginal Syllabics Extended-A\0"#
    240# -> "\192\26\1\0\255\26\1\0Pau Cin Hau\0"#
    241# -> "\0\27\1\0\95\27\1\0Devanagari Extended-A\0"#
    242# -> "\0\28\1\0\111\28\1\0Bhaiksuki\0"#
    243# -> "\112\28\1\0\191\28\1\0Marchen\0"#
    244# -> "\0\29\1\0\95\29\1\0Masaram Gondi\0"#
    245# -> "\96\29\1\0\175\29\1\0Gunjala Gondi\0"#
    246# -> "\224\30\1\0\255\30\1\0Makasar\0"#
    247# -> "\0\31\1\0\95\31\1\0Kawi\0"#
    248# -> "\176\31\1\0\191\31\1\0Lisu Supplement\0"#
    249# -> "\192\31\1\0\255\31\1\0Tamil Supplement\0"#
    250# -> "\0\32\1\0\255\35\1\0Cuneiform\0"#
    251# -> "\0\36\1\0\127\36\1\0Cuneiform Numbers and Punctuation\0"#
    252# -> "\128\36\1\0\79\37\1\0Early Dynastic Cuneiform\0"#
    253# -> "\144\47\1\0\255\47\1\0Cypro-Minoan\0"#
    254# -> "\0\48\1\0\47\52\1\0Egyptian Hieroglyphs\0"#
    255# -> "\48\52\1\0\95\52\1\0Egyptian Hieroglyph Format Controls\0"#
    256# -> "\0\68\1\0\127\70\1\0Anatolian Hieroglyphs\0"#
    257# -> "\0\104\1\0\63\106\1\0Bamum Supplement\0"#
    258# -> "\64\106\1\0\111\106\1\0Mro\0"#
    259# -> "\112\106\1\0\207\106\1\0Tangsa\0"#
    260# -> "\208\106\1\0\255\106\1\0Bassa Vah\0"#
    261# -> "\0\107\1\0\143\107\1\0Pahawh Hmong\0"#
    262# -> "\64\110\1\0\159\110\1\0Medefaidrin\0"#
    263# -> "\0\111\1\0\159\111\1\0Miao\0"#
    264# -> "\224\111\1\0\255\111\1\0Ideographic Symbols and Punctuation\0"#
    265# -> "\0\112\1\0\255\135\1\0Tangut\0"#
    266# -> "\0\136\1\0\255\138\1\0Tangut Components\0"#
    267# -> "\0\139\1\0\255\140\1\0Khitan Small Script\0"#
    268# -> "\0\141\1\0\127\141\1\0Tangut Supplement\0"#
    269# -> "\240\175\1\0\255\175\1\0Kana Extended-B\0"#
    270# -> "\0\176\1\0\255\176\1\0Kana Supplement\0"#
    271# -> "\0\177\1\0\47\177\1\0Kana Extended-A\0"#
    272# -> "\48\177\1\0\111\177\1\0Small Kana Extension\0"#
    273# -> "\112\177\1\0\255\178\1\0Nushu\0"#
    274# -> "\0\188\1\0\159\188\1\0Duployan\0"#
    275# -> "\160\188\1\0\175\188\1\0Shorthand Format Controls\0"#
    276# -> "\0\207\1\0\207\207\1\0Znamenny Musical Notation\0"#
    277# -> "\0\208\1\0\255\208\1\0Byzantine Musical Symbols\0"#
    278# -> "\0\209\1\0\255\209\1\0Musical Symbols\0"#
    279# -> "\0\210\1\0\79\210\1\0Ancient Greek Musical Notation\0"#
    280# -> "\192\210\1\0\223\210\1\0Kaktovik Numerals\0"#
    281# -> "\224\210\1\0\255\210\1\0Mayan Numerals\0"#
    282# -> "\0\211\1\0\95\211\1\0Tai Xuan Jing Symbols\0"#
    283# -> "\96\211\1\0\127\211\1\0Counting Rod Numerals\0"#
    284# -> "\0\212\1\0\255\215\1\0Mathematical Alphanumeric Symbols\0"#
    285# -> "\0\216\1\0\175\218\1\0Sutton SignWriting\0"#
    286# -> "\0\223\1\0\255\223\1\0Latin Extended-G\0"#
    287# -> "\0\224\1\0\47\224\1\0Glagolitic Supplement\0"#
    288# -> "\48\224\1\0\143\224\1\0Cyrillic Extended-D\0"#
    289# -> "\0\225\1\0\79\225\1\0Nyiakeng Puachue Hmong\0"#
    290# -> "\144\226\1\0\191\226\1\0Toto\0"#
    291# -> "\192\226\1\0\255\226\1\0Wancho\0"#
    292# -> "\208\228\1\0\255\228\1\0Nag Mundari\0"#
    293# -> "\224\231\1\0\255\231\1\0Ethiopic Extended-B\0"#
    294# -> "\0\232\1\0\223\232\1\0Mende Kikakui\0"#
    295# -> "\0\233\1\0\95\233\1\0Adlam\0"#
    296# -> "\112\236\1\0\191\236\1\0Indic Siyaq Numbers\0"#
    297# -> "\0\237\1\0\79\237\1\0Ottoman Siyaq Numbers\0"#
    298# -> "\0\238\1\0\255\238\1\0Arabic Mathematical Alphabetic Symbols\0"#
    299# -> "\0\240\1\0\47\240\1\0Mahjong Tiles\0"#
    300# -> "\48\240\1\0\159\240\1\0Domino Tiles\0"#
    301# -> "\160\240\1\0\255\240\1\0Playing Cards\0"#
    302# -> "\0\241\1\0\255\241\1\0Enclosed Alphanumeric Supplement\0"#
    303# -> "\0\242\1\0\255\242\1\0Enclosed Ideographic Supplement\0"#
    304# -> "\0\243\1\0\255\245\1\0Miscellaneous Symbols and Pictographs\0"#
    305# -> "\0\246\1\0\79\246\1\0Emoticons\0"#
    306# -> "\80\246\1\0\127\246\1\0Ornamental Dingbats\0"#
    307# -> "\128\246\1\0\255\246\1\0Transport and Map Symbols\0"#
    308# -> "\0\247\1\0\127\247\1\0Alchemical Symbols\0"#
    309# -> "\128\247\1\0\255\247\1\0Geometric Shapes Extended\0"#
    310# -> "\0\248\1\0\255\248\1\0Supplemental Arrows-C\0"#
    311# -> "\0\249\1\0\255\249\1\0Supplemental Symbols and Pictographs\0"#
    312# -> "\0\250\1\0\111\250\1\0Chess Symbols\0"#
    313# -> "\112\250\1\0\255\250\1\0Symbols and Pictographs Extended-A\0"#
    314# -> "\0\251\1\0\255\251\1\0Symbols for Legacy Computing\0"#
    315# -> "\0\0\2\0\223\166\2\0CJK Unified Ideographs Extension B\0"#
    316# -> "\0\167\2\0\63\183\2\0CJK Unified Ideographs Extension C\0"#
    317# -> "\64\183\2\0\31\184\2\0CJK Unified Ideographs Extension D\0"#
    318# -> "\32\184\2\0\175\206\2\0CJK Unified Ideographs Extension E\0"#
    319# -> "\176\206\2\0\239\235\2\0CJK Unified Ideographs Extension F\0"#
    320# -> "\0\248\2\0\31\250\2\0CJK Compatibility Ideographs Supplement\0"#
    321# -> "\0\0\3\0\79\19\3\0CJK Unified Ideographs Extension G\0"#
    322# -> "\80\19\3\0\175\35\3\0CJK Unified Ideographs Extension H\0"#
    323# -> "\0\0\14\0\127\0\14\0Tags\0"#
    324# -> "\0\1\14\0\239\1\14\0Variation Selectors Supplement\0"#
    325# -> "\0\0\15\0\255\255\15\0Supplementary Private Use Area-A\0"#
    326# -> "\0\0\16\0\255\255\16\0Supplementary Private Use Area-B\0"#
    _    -> "\0"#

-- | Character block, if defined, else -1.
--
-- @since 0.3.1
block :: Char# -> Int#
block c# = getBlock 0# 326#
    where
    -- [NOTE] Encoding
    -- A range is encoded as two LE Word32:
    -- • First one is the lower bound, where the higher 11 bits are the block
    --   index and the lower 21 bits are the codepoint.
    -- • Second one is the upper bound, which correspond to the codepoint.

    cp# = int2Word# (ord# c#)

    -- Binary search
    getBlock l# u# = if isTrue# (l# ># u#)
        then -1#
        else
            let k# = l# +# uncheckedIShiftRL# (u# -# l#) 1#
                j# = k# `uncheckedIShiftL#` 1#
                cpL0# = getRawCodePoint# j#
                cpL# = cpL0# `and#` 0x1fffff## -- Mask for codepoint: [0..0x10fff]
                cpU# = getRawCodePoint# (j# +# 1#)
            in if isTrue# (cpU# `ltWord#` cp#)
                -- cp > upper bound
                then getBlock (k# +# 1#) u#
                -- check lower bound
                else if isTrue# (cp# `ltWord#` cpL#)
                    -- cp < lower bound
                    then getBlock l# (k# -# 1#)
                    -- cp in block: get block index
                    else let block# = cpL0# `uncheckedShiftRL#` 21#
                         in word2Int# block#

    getRawCodePoint# = lookupWord32# ranges#

    -- Encoded ranges
    !(Ptr ranges#) = rangesBitmap

rangesBitmap :: Ptr Word32
rangesBitmap = Ptr
    "\0\0\0\0\127\0\0\0\128\0\32\0\255\0\0\0\0\1\64\0\127\1\0\0\128\1\96\0\79\2\0\0\80\2\128\0\175\2\0\0\176\2\160\0\255\2\0\0\0\3\192\0\111\3\0\0\112\3\224\0\255\3\0\0\0\4\0\1\255\4\0\0\0\5\32\1\47\5\0\0\48\5\64\1\143\5\0\0\144\5\96\1\255\5\0\0\0\6\128\1\255\6\0\0\0\7\160\1\79\7\0\0\80\7\192\1\127\7\0\0\128\7\224\1\191\7\0\0\192\7\0\2\255\7\0\0\0\8\32\2\63\8\0\0\64\8\64\2\95\8\0\0\96\8\96\2\111\8\0\0\112\8\128\2\159\8\0\0\160\8\160\2\255\8\0\0\0\9\192\2\127\9\0\0\128\9\224\2\255\9\0\0\0\10\0\3\127\10\0\0\128\10\32\3\255\10\0\0\0\11\64\3\127\11\0\0\128\11\96\3\255\11\0\0\0\12\128\3\127\12\0\0\128\12\160\3\255\12\0\0\0\13\192\3\127\13\0\0\128\13\224\3\255\13\0\
    \\0\0\14\0\4\127\14\0\0\128\14\32\4\255\14\0\0\0\15\64\4\255\15\0\0\0\16\96\4\159\16\0\0\160\16\128\4\255\16\0\0\0\17\160\4\255\17\0\0\0\18\192\4\127\19\0\0\128\19\224\4\159\19\0\0\160\19\0\5\255\19\0\0\0\20\32\5\127\22\0\0\128\22\64\5\159\22\0\0\160\22\96\5\255\22\0\0\0\23\128\5\31\23\0\0\32\23\160\5\63\23\0\0\64\23\192\5\95\23\0\0\96\23\224\5\127\23\0\0\128\23\0\6\255\23\0\0\0\24\32\6\175\24\0\0\176\24\64\6\255\24\0\0\0\25\96\6\79\25\0\0\80\25\128\6\127\25\0\0\128\25\160\6\223\25\0\0\224\25\192\6\255\25\0\0\0\26\224\6\31\26\0\0\32\26\0\7\175\26\0\0\176\26\32\7\255\26\0\0\0\27\64\7\127\27\0\0\128\27\96\7\191\27\0\0\192\27\128\7\255\27\0\0\0\28\160\7\79\28\0\0\80\28\192\7\127\28\0\0\128\28\224\7\143\28\
    \\0\0\144\28\0\8\191\28\0\0\192\28\32\8\207\28\0\0\208\28\64\8\255\28\0\0\0\29\96\8\127\29\0\0\128\29\128\8\191\29\0\0\192\29\160\8\255\29\0\0\0\30\192\8\255\30\0\0\0\31\224\8\255\31\0\0\0\32\0\9\111\32\0\0\112\32\32\9\159\32\0\0\160\32\64\9\207\32\0\0\208\32\96\9\255\32\0\0\0\33\128\9\79\33\0\0\80\33\160\9\143\33\0\0\144\33\192\9\255\33\0\0\0\34\224\9\255\34\0\0\0\35\0\10\255\35\0\0\0\36\32\10\63\36\0\0\64\36\64\10\95\36\0\0\96\36\96\10\255\36\0\0\0\37\128\10\127\37\0\0\128\37\160\10\159\37\0\0\160\37\192\10\255\37\0\0\0\38\224\10\255\38\0\0\0\39\0\11\191\39\0\0\192\39\32\11\239\39\0\0\240\39\64\11\255\39\0\0\0\40\96\11\255\40\0\0\0\41\128\11\127\41\0\0\128\41\160\11\255\41\0\0\0\42\192\11\255\42\0\0\0\43\224\11\255\
    \\43\0\0\0\44\0\12\95\44\0\0\96\44\32\12\127\44\0\0\128\44\64\12\255\44\0\0\0\45\96\12\47\45\0\0\48\45\128\12\127\45\0\0\128\45\160\12\223\45\0\0\224\45\192\12\255\45\0\0\0\46\224\12\127\46\0\0\128\46\0\13\255\46\0\0\0\47\32\13\223\47\0\0\240\47\64\13\255\47\0\0\0\48\96\13\63\48\0\0\64\48\128\13\159\48\0\0\160\48\160\13\255\48\0\0\0\49\192\13\47\49\0\0\48\49\224\13\143\49\0\0\144\49\0\14\159\49\0\0\160\49\32\14\191\49\0\0\192\49\64\14\239\49\0\0\240\49\96\14\255\49\0\0\0\50\128\14\255\50\0\0\0\51\160\14\255\51\0\0\0\52\192\14\191\77\0\0\192\77\224\14\255\77\0\0\0\78\0\15\255\159\0\0\0\160\32\15\143\164\0\0\144\164\64\15\207\164\0\0\208\164\96\15\255\164\0\0\0\165\128\15\63\166\0\0\64\166\160\15\159\166\0\0\160\166\192\15\255\166\0\0\0\167\224\15\
    \\31\167\0\0\32\167\0\16\255\167\0\0\0\168\32\16\47\168\0\0\48\168\64\16\63\168\0\0\64\168\96\16\127\168\0\0\128\168\128\16\223\168\0\0\224\168\160\16\255\168\0\0\0\169\192\16\47\169\0\0\48\169\224\16\95\169\0\0\96\169\0\17\127\169\0\0\128\169\32\17\223\169\0\0\224\169\64\17\255\169\0\0\0\170\96\17\95\170\0\0\96\170\128\17\127\170\0\0\128\170\160\17\223\170\0\0\224\170\192\17\255\170\0\0\0\171\224\17\47\171\0\0\48\171\0\18\111\171\0\0\112\171\32\18\191\171\0\0\192\171\64\18\255\171\0\0\0\172\96\18\175\215\0\0\176\215\128\18\255\215\0\0\0\216\160\18\127\219\0\0\128\219\192\18\255\219\0\0\0\220\224\18\255\223\0\0\0\224\0\19\255\248\0\0\0\249\32\19\255\250\0\0\0\251\64\19\79\251\0\0\80\251\96\19\255\253\0\0\0\254\128\19\15\254\0\0\16\254\160\19\31\254\0\0\32\254\192\19\47\254\0\0\48\254\224\
    \\19\79\254\0\0\80\254\0\20\111\254\0\0\112\254\32\20\255\254\0\0\0\255\64\20\239\255\0\0\240\255\96\20\255\255\0\0\0\0\129\20\127\0\1\0\128\0\161\20\255\0\1\0\0\1\193\20\63\1\1\0\64\1\225\20\143\1\1\0\144\1\1\21\207\1\1\0\208\1\33\21\255\1\1\0\128\2\65\21\159\2\1\0\160\2\97\21\223\2\1\0\224\2\129\21\255\2\1\0\0\3\161\21\47\3\1\0\48\3\193\21\79\3\1\0\80\3\225\21\127\3\1\0\128\3\1\22\159\3\1\0\160\3\33\22\223\3\1\0\0\4\65\22\79\4\1\0\80\4\97\22\127\4\1\0\128\4\129\22\175\4\1\0\176\4\161\22\255\4\1\0\0\5\193\22\47\5\1\0\48\5\225\22\111\5\1\0\112\5\1\23\191\5\1\0\0\6\33\23\127\7\1\0\128\7\65\23\191\7\1\0\0\8\97\23\63\8\1\0\64\8\129\23\95\8\1\0\96\8\161\23\127\8\1\0\128\8\193\23\175\8\1\0\224\8\
    \\225\23\255\8\1\0\0\9\1\24\31\9\1\0\32\9\33\24\63\9\1\0\128\9\65\24\159\9\1\0\160\9\97\24\255\9\1\0\0\10\129\24\95\10\1\0\96\10\161\24\127\10\1\0\128\10\193\24\159\10\1\0\192\10\225\24\255\10\1\0\0\11\1\25\63\11\1\0\64\11\33\25\95\11\1\0\96\11\65\25\127\11\1\0\128\11\97\25\175\11\1\0\0\12\129\25\79\12\1\0\128\12\161\25\255\12\1\0\0\13\193\25\63\13\1\0\96\14\225\25\127\14\1\0\128\14\1\26\191\14\1\0\192\14\33\26\255\14\1\0\0\15\65\26\47\15\1\0\48\15\97\26\111\15\1\0\112\15\129\26\175\15\1\0\176\15\161\26\223\15\1\0\224\15\193\26\255\15\1\0\0\16\225\26\127\16\1\0\128\16\1\27\207\16\1\0\208\16\33\27\255\16\1\0\0\17\65\27\79\17\1\0\80\17\97\27\127\17\1\0\128\17\129\27\223\17\1\0\224\17\161\27\255\17\1\0\0\18\193\27\79\18\1\0\128\
    \\18\225\27\175\18\1\0\176\18\1\28\255\18\1\0\0\19\33\28\127\19\1\0\0\20\65\28\127\20\1\0\128\20\97\28\223\20\1\0\128\21\129\28\255\21\1\0\0\22\161\28\95\22\1\0\96\22\193\28\127\22\1\0\128\22\225\28\207\22\1\0\0\23\1\29\79\23\1\0\0\24\33\29\79\24\1\0\160\24\65\29\255\24\1\0\0\25\97\29\95\25\1\0\160\25\129\29\255\25\1\0\0\26\161\29\79\26\1\0\80\26\193\29\175\26\1\0\176\26\225\29\191\26\1\0\192\26\1\30\255\26\1\0\0\27\33\30\95\27\1\0\0\28\65\30\111\28\1\0\112\28\97\30\191\28\1\0\0\29\129\30\95\29\1\0\96\29\161\30\175\29\1\0\224\30\193\30\255\30\1\0\0\31\225\30\95\31\1\0\176\31\1\31\191\31\1\0\192\31\33\31\255\31\1\0\0\32\65\31\255\35\1\0\0\36\97\31\127\36\1\0\128\36\129\31\79\37\1\0\144\47\161\31\255\47\1\0\0\48\193\31\47\52\1\0\
    \\48\52\225\31\95\52\1\0\0\68\1\32\127\70\1\0\0\104\33\32\63\106\1\0\64\106\65\32\111\106\1\0\112\106\97\32\207\106\1\0\208\106\129\32\255\106\1\0\0\107\161\32\143\107\1\0\64\110\193\32\159\110\1\0\0\111\225\32\159\111\1\0\224\111\1\33\255\111\1\0\0\112\33\33\255\135\1\0\0\136\65\33\255\138\1\0\0\139\97\33\255\140\1\0\0\141\129\33\127\141\1\0\240\175\161\33\255\175\1\0\0\176\193\33\255\176\1\0\0\177\225\33\47\177\1\0\48\177\1\34\111\177\1\0\112\177\33\34\255\178\1\0\0\188\65\34\159\188\1\0\160\188\97\34\175\188\1\0\0\207\129\34\207\207\1\0\0\208\161\34\255\208\1\0\0\209\193\34\255\209\1\0\0\210\225\34\79\210\1\0\192\210\1\35\223\210\1\0\224\210\33\35\255\210\1\0\0\211\65\35\95\211\1\0\96\211\97\35\127\211\1\0\0\212\129\35\255\215\1\0\0\216\161\35\175\218\1\0\0\223\193\35\255\223\1\
    \\0\0\224\225\35\47\224\1\0\48\224\1\36\143\224\1\0\0\225\33\36\79\225\1\0\144\226\65\36\191\226\1\0\192\226\97\36\255\226\1\0\208\228\129\36\255\228\1\0\224\231\161\36\255\231\1\0\0\232\193\36\223\232\1\0\0\233\225\36\95\233\1\0\112\236\1\37\191\236\1\0\0\237\33\37\79\237\1\0\0\238\65\37\255\238\1\0\0\240\97\37\47\240\1\0\48\240\129\37\159\240\1\0\160\240\161\37\255\240\1\0\0\241\193\37\255\241\1\0\0\242\225\37\255\242\1\0\0\243\1\38\255\245\1\0\0\246\33\38\79\246\1\0\80\246\65\38\127\246\1\0\128\246\97\38\255\246\1\0\0\247\129\38\127\247\1\0\128\247\161\38\255\247\1\0\0\248\193\38\255\248\1\0\0\249\225\38\255\249\1\0\0\250\1\39\111\250\1\0\112\250\33\39\255\250\1\0\0\251\65\39\255\251\1\0\0\0\98\39\223\166\2\0\0\167\130\39\63\183\2\0\64\183\162\39\31\184\2\0\32\184\194\39\175\206\
    \\2\0\176\206\226\39\239\235\2\0\0\248\2\40\31\250\2\0\0\0\35\40\79\19\3\0\80\19\67\40\175\35\3\0\0\0\110\40\127\0\14\0\0\1\142\40\239\1\14\0\0\0\175\40\255\255\15\0\0\0\208\40\255\255\16\0"#
